// =============================================================================
// memax-sdk — TypeScript SDK for the Memax API
// Works in Node.js, Deno, and edge runtimes (uses fetch, not http)
// =============================================================================

export { Memax } from "./client.js";
export {
  NEEDS_ACTION_KINDS,
  NOTIFICATION_KINDS,
  UPDATES_KINDS,
  isNeedsActionKind,
  classifyAgentConfigFile,
} from "./types.js";
export type { EventsSubscribeOptions } from "./resources/events.js";
export type { NotificationItemUpdateResult } from "./resources/notifications.js";

// Plan 18 — super-notif primitives (shared Item shape + payload types
// + the kind/action → resolution map). These are deliberately surfaced
// from the public SDK so producers and renderers can both consume them
// without re-encoding the wire shape.
export type {
  Item,
  ChecklistItem,
  DigestItem,
  ItemProgress,
  PinContext,
  ChecklistPayload,
  DigestPayload,
} from "./notifications/items.js";
export { SUPER_NOTIF_KINDS } from "./notifications/items.js";
export {
  actionToResolution,
  resolveFromAction,
} from "./notifications/action-to-resolution.js";
// Admin APIs are an internal, web-only surface and are intentionally not
// exported by this public SDK.
export { MemaxError } from "./errors.js";

// /v2 — the V2 record. Types are generated from
// packages/server/openapi/v2.yaml; use them as `V2.Memory`, `V2.PolicyCode`…
// (`export * as`, not `export type * as`, so the .d.ts parses on
// TypeScript before 5.0; the module holds only types.)
export * as V2 from "./v2/types.js";
export {
  V2Resource,
  V2SpacesResource,
  V2MemoriesResource,
  V2ReviewResource,
  V2ReceiptsResource,
  V2ReadsResource,
  V2AgentsResource,
  V2BriefsResource,
  V2TargetsResource,
  V2GatesResource,
  V2NoticesResource,
  V2DreamResource,
  V2SettingsResource,
  undoableAction,
  refusalOf,
  forgetCarriesOf,
  askEventOf,
} from "./v2/resources.js";
export { EventStreamParser, readEventStream } from "./v2/sse.js";
export type { ServerSentEvent } from "./v2/sse.js";
export {
  verifyReceiptChain,
  canonicalReceipt,
  checkpointStatement,
  receiptLeaf,
  genesisHash,
  merkleRoot,
} from "./v2/verify.js";
export type {
  ChainReceipt,
  ChainReport,
  ChainProblem,
  ChainProblemKind,
  ChainCrypto,
  VerifyChainInput,
} from "./v2/verify.js";
export {
  EXPORT_FORMAT,
  ExportFormatError,
  parseExport,
  parseFrontmatter,
  parseReceipts,
  splitDocument,
  verifyExport,
} from "./v2/export.js";
export type {
  ExportFiles,
  ExportManifest,
  ExportManifestFile,
  ExportCheckpoints,
  ExportReceiptStamp,
  ExportedMemory,
  ExportedTombstone,
  ExportedBrief,
  ParsedExport,
  ExportProblem,
  ExportProblemKind,
  ExportReport,
  VerifyExportInput,
} from "./v2/export.js";
export type {
  CommandOptions as V2CommandOptions,
  MemoryRefOptions as V2MemoryRefOptions,
  ReviewOptions as V2ReviewOptions,
  EditOptions as V2EditOptions,
  PageOptions as V2PageOptions,
  VersionedCommandOptions as V2VersionedCommandOptions,
  ListMemoriesOptions as V2ListMemoriesOptions,
  ListReceiptsOptions as V2ListReceiptsOptions,
  GetMemoryOptions as V2GetMemoryOptions,
  ListGatesOptions as V2ListGatesOptions,
  GateRefOptions as V2GateRefOptions,
  GateCommandOptions as V2GateCommandOptions,
  AskOptions as V2AskOptions,
  SpaceExport as V2SpaceExport,
  SettingsEditOptions as V2SettingsEditOptions,
} from "./v2/resources.js";
export type {
  // Config
  MemaxConfig,
  AuthProvider,
  // Request options
  PushOptions,
  RecallOptions,
  AskOptions,
  ListMemoriesOptions,
  HubUpdateParams,
  // Core domain
  MemoryKind,
  MemoryStability,
  Memory,
  MemoryAttachment,
  AttachmentViewURL,
  MemoryLifecycle,
  MemoryUpdateInput,
  DreamActionRef,
  DreamTopicRef,
  ShareMemoryResult,
  BatchMoveResult,
  BatchAttributeResult,
  BatchMoveSkippedMemory,
  BatchMoveSkipReason,
  BatchDeleteResult,
  BatchDeleteSkippedMemory,
  BatchDeleteSkipReason,
  AgentConfigBatchDeleteResult,
  AgentConfigDeleteSkippedItem,
  AgentConfigDeleteSkipReason,
  RelatedMemory,
  RecalledMemory,
  RecallResult,
  SearchResult,
  BarSearchResult,
  BarTopicMatch,
  BarHubMatch,
  AskResult,
  ListMemoriesResult,
  // Agent configs
  Scope,
  AgentConfigClass,
  AgentConfig,
  Persona,
  PersonaRevision,
  PersonaRestoreResult,
  // Boards (pulse boards)
  BoardKind,
  BoardStatus,
  BoardSlotState,
  BoardSlotAction,
  BoardFeedbackVerdict,
  Board,
  BoardSlotResolution,
  BoardSlot,
  BoardSlotVersion,
  BoardWithSlots,
  AgentConfigListResult,
  DeletedAgentConfig,
  SyncAction,
  SyncPlanAction,
  SyncManifestEntry,
  ConfigSyncRequest,
  AgentConfigSyncAck,
  ConfigSyncAckRequest,
  ConfigLocalDeleteRequest,
  RestoreDeletedConfigRequest,
  ConfigUpsertRequest,
  ConfigMergeRequest,
  UploadIntent,
  // Auth
  AuthProviderName,
  User,
  MeResponse,
  AuthTokenPair,
  DeviceSignIn,
  DeviceSignInOptions,
  DeviceSignInPoll,
  ImpersonationResult,
  AuthIdentity,
  UnlinkProviderResult,
  RequestEmailOtpOptions,
  RequestEmailOtpResponse,
  VerifyEmailOtpOptions,
  VerifyEmailOtpResponse,
  ApiKeyCreateOptions,
  ApiKey,
  ApiKeyListItem,
  UpdateApiKeyPayload,
  UpdateApiKeyResult,
  OAuthConsentHub,
  OAuthConsentPermission,
  OAuthConsentRequest,
  UpdateProfileResult,
  DeleteAllDataResult,
  // Hubs
  Hub,
  HubSettings,
  HubSettingsInput,
  HubWithRole,
  HubMember,
  HubInvite,
  HubInviteeInput,
  HubOwnershipTransfer,
  HubDetailResult,
  HubSummary,
  HubSummaryStats,
  HubSummaryHeader,
  HubSummaryMember,
  HubAccent,
  HubRole,
  HubType,
  HubHeaderState,
  HubHeaderAuroraMode,
  HubTimeBucket,
  HubGreetingKey,
  ContributorDeletePolicy,
  InviteDetails,
  InviteAcceptResult,
  // Settings & usage
  DevFlagsSettings,
  Settings,
  SettingsUpdateInput,
  Usage,
  UsageWithLimits,
  // Plans
  PlanScope,
  PlanDefinition,
  UserLimits,
  // Topics
  Topic,
  TopicLifecycle,
  TopicDeltaSummary,
  TopicTree,
  TopicListResponse,
  TopicArchivedListResponse,
  TopicArchiveResult,
  TopicCreateParams,
  TopicUpdateParams,
  TopicUpdateErrorCode,
  TopicReorderOperation,
  TopicMemoriesResponse,
  // Dreams
  DreamRun,
  DreamAction,
  DreamLatestRunSummary,
  DreamPendingReviewSummary,
  DreamIntelligenceSummary,
  DreamReport,
  DreamRunListOptions,
  DreamRunListResponse,
  DreamUsage,
  DreamUsageOptions,
  ReviewTopicMergePayload,
  ReviewTopicRestructurePayload,
  ReviewTopicRef,
  // Notifications
  Notification,
  NotificationAudience,
  NotificationStatus,
  NotificationResolution,
  NotificationKind,
  NeedsActionNotificationKind,
  UpdateNotificationKind,
  NotificationKindCount,
  NotificationSummary,
  NotificationListQuery,
  NotificationListResponse,
  NotificationBulkQuery,
  NotificationBulkResult,
  NotificationResolveAction,
  NotificationResolveResult,
  ReviewContradictionPayload,
  ReviewMemoryRef,
  DreamRunCompletedPayload,
  DreamRunCounts,
  HubInvitePayload,
  HubInviteHubRef,
  HubInviteInviterRef,
  HubMemberJoinedPayload,
  HubMemberRef,
  HubInviteAcceptedPayload,
  HubInviteDeclinedPayload,
  HubInviteDeclinedByYouPayload,
  HubOwnershipTransferPayload,
  HubOwnershipTransferredPayload,
  SystemNoticePayload,
  GiftInviteLinkPayload,
  // Connected agents
  ConnectedAgent,
  ConnectedAgentWithStats,
  ConnectedAgentUpdate,
  DisconnectAgentResult,
  AgentDisconnectSkipReason,
  AgentDisconnectSkippedItem,
  ApiKeyRevokeResult,
  ApiKeyRevokeSkipReason,
  ApiKeyRevokeSkippedItem,
  // Chat
  ChatScopeType,
  ChatSessionStatus,
  ChatMessageRole,
  ChatMessageStatus,
  ChatSession,
  ChatMessage,
  ChatToolDescriptor,
  CreateChatSessionInput,
  PatchChatSessionInput,
  ListChatSessionsOptions,
  ListChatSessionsResult,
  ListChatMessagesOptions,
  ListChatMessagesResult,
  ChatTurnOutcome,
  SendChatMessageInput,
  SendChatMessageResult,
  CancelChatMessageResult,
  RegenerateChatMessageResult,
  DecideApprovalResult,
  ChatStreamOptions,
  ChatStreamEventName,
} from "./types.js";
