// =============================================================================
// memax-sdk — TypeScript SDK for the Memax API
// Works in Node.js, Deno, and edge runtimes (uses fetch, not http)
// =============================================================================

export { Memax } from "./client.js";
export {
  NEEDS_ACTION_KINDS,
  NOTIFICATION_KINDS,
  UPDATES_KINDS,
  isNeedsActionKind,
} from "./types.js";
export type { EventsSubscribeOptions } from "./resources/events.js";
// Admin APIs are an internal, web-only surface and are intentionally not
// exported by this public SDK.
export { MemaxError } from "./errors.js";
export type {
  // Config
  MemaxConfig,
  AuthProvider,
  // Request options
  PushOptions,
  RecallOptions,
  AskOptions,
  ListMemoriesOptions,
  HubUpdateParams,
  // Core domain
  MemoryKind,
  MemoryStability,
  Memory,
  MemoryAttachment,
  AttachmentViewURL,
  MemoryLifecycle,
  MemoryUpdateInput,
  DreamActionRef,
  DreamTopicRef,
  ShareMemoryResult,
  BatchMoveResult,
  BatchMoveSkippedMemory,
  BatchMoveSkipReason,
  BatchDeleteResult,
  BatchDeleteSkippedMemory,
  BatchDeleteSkipReason,
  AgentConfigBatchDeleteResult,
  AgentConfigDeleteSkippedItem,
  AgentConfigDeleteSkipReason,
  RelatedMemory,
  RecalledMemory,
  RecallResult,
  SearchResult,
  BarSearchResult,
  BarTopicMatch,
  BarHubMatch,
  AskResult,
  ListMemoriesResult,
  // Agent configs
  Scope,
  AgentConfig,
  AgentConfigListResult,
  DeletedAgentConfig,
  SyncAction,
  SyncPlanAction,
  SyncManifestEntry,
  ConfigSyncRequest,
  AgentConfigSyncAck,
  ConfigSyncAckRequest,
  ConfigLocalDeleteRequest,
  RestoreDeletedConfigRequest,
  ConfigUpsertRequest,
  ConfigMergeRequest,
  UploadIntent,
  AgentSession,
  DeletedAgentSession,
  SessionSyncAction,
  SessionSyncPlanAction,
  SessionSyncManifestEntry,
  AgentSessionSyncRequest,
  AgentSessionSyncAck,
  AgentSessionSyncAckRequest,
  AgentSessionLocalDeleteRequest,
  RestoreDeletedSessionRequest,
  AgentSessionUpsertRequest,
  ResolveDivergenceRequest,
  ResolveDivergenceResponse,
  // Auth
  AuthProviderName,
  User,
  MeResponse,
  AuthTokenPair,
  ImpersonationResult,
  AuthIdentity,
  UnlinkProviderResult,
  ApiKeyCreateOptions,
  ApiKey,
  ApiKeyListItem,
  UpdateApiKeyPayload,
  UpdateApiKeyResult,
  OAuthConsentHub,
  OAuthConsentPermission,
  OAuthConsentRequest,
  UpdateProfileResult,
  DeleteAllDataResult,
  // Hubs
  Hub,
  HubSettings,
  HubSettingsInput,
  HubWithRole,
  HubMember,
  HubInvite,
  HubInviteeInput,
  HubOwnershipTransfer,
  HubDetailResult,
  HubSummary,
  HubSummaryStats,
  HubSummaryHeader,
  HubSummaryMember,
  HubAccent,
  HubRole,
  HubType,
  HubHeaderState,
  HubHeaderAuroraMode,
  HubTimeBucket,
  HubGreetingKey,
  ContributorDeletePolicy,
  InviteDetails,
  InviteAcceptResult,
  // Settings & usage
  DevFlagsSettings,
  Settings,
  SettingsUpdateInput,
  Usage,
  UsageWithLimits,
  // Plans
  PlanScope,
  PlanDefinition,
  UserLimits,
  // Topics
  Topic,
  TopicLifecycle,
  TopicDeltaSummary,
  TopicTree,
  TopicListResponse,
  TopicCreateParams,
  TopicUpdateParams,
  TopicUpdateErrorCode,
  TopicReorderOperation,
  TopicMemoriesResponse,
  // Dreams
  DreamRun,
  DreamAction,
  DreamLatestRunSummary,
  DreamPendingReviewSummary,
  DreamIntelligenceSummary,
  DreamReport,
  DreamRunListOptions,
  DreamRunListResponse,
  ReviewTopicMergePayload,
  ReviewTopicRestructurePayload,
  ReviewTopicRef,
  // Notifications
  Notification,
  NotificationAudience,
  NotificationStatus,
  NotificationResolution,
  NotificationKind,
  NeedsActionNotificationKind,
  UpdateNotificationKind,
  NotificationKindCount,
  NotificationSummary,
  NotificationListQuery,
  NotificationListResponse,
  NotificationBulkQuery,
  NotificationBulkResult,
  NotificationResolveAction,
  NotificationResolveResult,
  ReviewContradictionPayload,
  ReviewMemoryRef,
  DreamRunCompletedPayload,
  DreamRunCounts,
  HubInvitePayload,
  HubInviteHubRef,
  HubInviteInviterRef,
  HubMemberJoinedPayload,
  HubMemberRef,
  HubInviteAcceptedPayload,
  HubInviteDeclinedPayload,
  HubInviteDeclinedByYouPayload,
  HubOwnershipTransferPayload,
  HubOwnershipTransferredPayload,
  SystemNoticePayload,
  GiftInviteLinkPayload,
  // Connected agents
  ConnectedAgent,
  ConnectedAgentWithStats,
  ConnectedAgentUpdate,
  DisconnectAgentResult,
  AgentDisconnectSkipReason,
  AgentDisconnectSkippedItem,
  ApiKeyRevokeResult,
  ApiKeyRevokeSkipReason,
  ApiKeyRevokeSkippedItem,
} from "./types.js";
